# Generated by Django 4.2.21 on 2025-06-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='custom_category',
            field=models.CharField(blank=True, help_text='기타를 선택한 경우 여기에 직접 입력하세요', max_length=50, verbose_name='사용자 지정 카테고리'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('vegetable', '야채'), ('fruit', '과일'), ('meat', '정육(육류)'), ('seafood', '해산물'), ('dairy', '유제품'), ('egg', '계란'), ('frozen', '냉동식품'), ('seasoning', '양념·조미료'), ('beverage', '음료'), ('other', '기타')], default='vegetable', max_length=20, verbose_name='카테고리'),
        ),
    ]
