# Generated by Django 4.2.21 on 2025-06-06 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_ingredient_custom_category_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '사용자 설정', 'verbose_name_plural': '사용자 설정들'},
        ),
        migrations.AddField(
            model_name='settings',
            name='alert_day_major',
            field=models.PositiveSmallIntegerField(default=3, help_text='유통기한 며칠 전에 첫 번째 알림을 받을지 설정하세요.', verbose_name='첫 번째 알림(며칠 전)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='alert_day_minor',
            field=models.PositiveSmallIntegerField(default=1, help_text='유통기한 며칠 전에 마지막 알림을 받을지 설정하세요.', verbose_name='두 번째 알림(며칠 전)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_cook_time',
            field=models.PositiveIntegerField(default=30, help_text='요리 추천 시 기본으로 사용할 예상 조리 시간(분)입니다.', verbose_name='기본 시간(분)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_difficulty',
            field=models.CharField(default='Easy', help_text='요리 추천 시 기본으로 사용할 난이도입니다.', max_length=20, verbose_name='기본 난이도'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='push_badge_alert',
            field=models.BooleanField(default=True, help_text='뱃지 획득 알림을 받을지 설정합니다.', verbose_name='뱃지 알림'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='push_expiry_alert',
            field=models.BooleanField(default=True, help_text='유통기한 임박 알림을 받을지 설정합니다.', verbose_name='알림 허용'),
        ),
    ]
