# Generated by Django 4.2.21 on 2025-06-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_settings_options_settings_alert_day_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='color_count_1',
            field=models.CharField(default='#90ee90', max_length=7, verbose_name='아침/점심/저녁 1회 색상'),
        ),
        migrations.AddField(
            model_name='settings',
            name='color_count_2',
            field=models.CharField(default='#ffd700', max_length=7, verbose_name='2회 색상'),
        ),
        migrations.AddField(
            model_name='settings',
            name='color_count_3',
            field=models.CharField(default='#ff6347', max_length=7, verbose_name='3회 이상 색상'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='alert_day_minor',
            field=models.PositiveSmallIntegerField(default=1, help_text='유통기한 며칠 전에 마지막 알림을 받을지 설정하세요.', verbose_name='마지막 알림(며칠 전)'),
        ),
    ]
