# Generated by Django 4.2.21 on 2025-06-15 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_settings_color_count_1_settings_color_count_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='graph_color',
            field=models.CharField(default='#4bc0c0', max_length=7),
        ),
        migrations.AlterField(
            model_name='settings',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
