# Generated by Django 4.2.23 on 2025-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_settings_graph_color_alter_settings_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='member',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='ShelfLifeData',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='color_count_1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='color_count_2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='color_count_3',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='default_cook_time',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='default_difficulty',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='push_badge_alert',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
